version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[MISC] "
    include: scope
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
  - dependency-name: "@craco/craco"
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
  - dependency-name: "@fortawesome/free-regular-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  commit-message:
    prefix: "[MISC] "
    include: scope
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github-pages
    versions:
    - "211"
    - "212"
    - "213"
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  commit-message:
    prefix: "[MISC] "
    include: scope
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: arm32v7/alpine
    versions:
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  - dependency-name: arm64v8/alpine
    versions:
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  - dependency-name: alpine
    versions:
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  - dependency-name: golang
    versions:
    - 1.15.7.pre.alpine
    - 1.15.8.pre.alpine
    - 1.16.0.pre.alpine
    - 1.16.1.pre.alpine
    - 1.16.2.pre.alpine
  commit-message:
    prefix: "[MISC] "
    include: scope
- package-ecosystem: docker
  directory: "/internal/suites/example/compose/authelia"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: golang
    versions:
    - 1.15.7.pre.alpine
    - 1.15.8.pre.alpine
    - 1.16.0.pre.alpine
    - 1.16.1.pre.alpine
    - 1.16.2.pre.alpine
  commit-message:
    prefix: "[MISC] "
    include: scope
- package-ecosystem: docker
  directory: "/internal/suites/example/compose/haproxy"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: haproxy
    versions:
    - 2.3.4.pre.alpine
    - 2.3.5.pre.alpine
    - 2.3.6.pre.alpine
    - 2.3.7.pre.alpine
    - 2.3.8.pre.alpine
    - 2.3.9.pre.alpine
  commit-message:
    prefix: "[MISC] "
    include: scope
- package-ecosystem: docker
  directory: "/internal/suites/example/compose/duo-api"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[MISC] "
    include: scope
- package-ecosystem: docker
  directory: "/internal/suites/example/compose/kind"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  commit-message:
    prefix: "[MISC] "
    include: scope
